### PR TITLE
Added Online Safety sections.

### PR DESCRIPTION
**Pull request by deammer**

### CODE REVIEW

**Comment by deammer** [comment]
Conflicts resolved!

**Comment by deammer** [comment]
Hey @csb324 is this of interest? If so, I can fix the conflicts again :)

**Comment by justinxreese** [comment]
Thanks to @binford2k for pointing me to this PR. It is indeed similar to my issue raised in #10 and I'd consider this a good resolution of it as-is. Minor suggestions: @deammer, you should consider adding donations to the EFF and info on using VPNs. I think the biggest reason #10 doesn't have any code behind it was my hesitancy recommending any particular VPN service. No tor/signal equivalents in terms of trustworthiness that I knew of personally.

**Comment by deammer** [comment]
@justinxreese I can definitely add the EFF in there. I don't feel confident recommending a VPN either, though.

**Pull request closed without merging**
